import type { Metadata } from "next";
import { Suspense } from "react";
import "./styles/styles.css"; // Or your main stylesheet file

import Header from "./blocks/header/header";
import Highlight from "./blocks/highlight/highlight";
import Footer from "./blocks/footer/footer";
import ErrorBoundary from "./components/ErrorBoundary/ErrorBoundary";
import Loading from "./components/Loading/Loading";

export const metadata: Metadata = {
  title: "My NGC Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ErrorBoundary>
          <Suspense fallback={<Loading message="Loading header..." />}>
            <Highlight />
            <Header />
          </Suspense>
          <main>
            <Suspense fallback={<Loading message="Loading content..." fullScreen />}>
              {children}
            </Suspense>
          </main>
          <Suspense fallback={<Loading message="Loading footer..." />}>
            <Footer />
          </Suspense>
        </ErrorBoundary>
      </body>
    </html>
  );
}