import type { Metadata } from "next";
import "./styles/styles.css"; // Or your main stylesheet file

import Header from "./blocks/header/header";
import Highlight from "./blocks/highlight/highlight";
import Footer from "./blocks/footer/footer";
import ErrorBoundary from "./components/ErrorBoundary/ErrorBoundary";

export const metadata: Metadata = {
  title: "My NGC Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ErrorBoundary>
          <Highlight />
          <Header />
          <main>{children}</main>
          <Footer />
        </ErrorBoundary>
      </body>
    </html>
  );
}