import type { Metadata } from "next";
import "./styles/styles.css"; // Or your main stylesheet file

import Header from "./blocks/header/header";
import Highlight from "./blocks/highlight/highlight";
import ScrollLockHandler from "./components/ScrollLockHandler";

export const metadata: Metadata = {
  title: "My NGC Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Highlight />
        <Header />
        <main>{children}</main>
        <ScrollLockHandler />
      </body>
    </html>
  );
}